//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje
{
    using System;
    using System.Collections.Generic;
    
    public partial class Satis
    {
        public int ID { get; set; }
        public string Tc { get; set; }
        public string AdSoyad { get; set; }
        public string telefon { get; set; }
        public string BarkodNo { get; set; }
        public string UrunAdi { get; set; }
        public Nullable<int> miktari { get; set; }
        public string SatisFiyati { get; set; }
        public string ToplamFiyat { get; set; }
        public string tarih { get; set; }
    }
}
