//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urun
    {
        public int ID { get; set; }
        public string BarkodNo { get; set; }
        public string UrunAdi { get; set; }
        public string Marka { get; set; }
        public string Kategori { get; set; }
        public string Stok { get; set; }
        public string SatisFiyati { get; set; }
    }
}
